### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by bounmed** [charming-chino/charming-chino#81]
I tried to install this application but i get this error after i run grunt:
This is my envirement:
macOS Sierra 10.12.6 
#ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
#node -v
v6.9.1
#npm -v
5.4.2
#grunt --version
grunt-cli v1.2.0
grunt v0.4.5

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at module.exports (/Applications/AMPPS/www/sunday-cook.js/trunk/server/express/passport.js:19:37)
    at Object.<anonymous> (/Applications/AMPPS/www/sunday-cook.js/trunk/server/express/express.js:49:39)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/AMPPS/www/sunday-cook.js/trunk/server/server.js:2:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by kamronbatman** [comment]
Sorry but this project is not being maintained.
